sudo: required

language: bash

services:
  - docker

script:
    - docker build -t vect0r/nginx-crl-check .

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push vect0r/nginx-crl-check;
      fi
